name: CI
on:
  push:
  pull_request:
  workflow_run:
    workflows: ["Update Shiki"]
    branches:
      - main
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
